### ISSUE TITLE
High quality images needed.

### ISSUE THREAD

**Issue by dreamknight0** [Kanaries/Rath#280]
Can we provide high quality images for download?

**Comment by ObservedObserver** [comment]
It is already supported, you can click the `export button` on the toolbar. (PNG and SVG are supported)

If you'd like to download images with custom size and PPI config, it can be supported in recent updates in future.

**Comment by AntoineYANG** [comment]
Hi @dreamknight0,
thanks and sure that would be great! 

Advanced options of exporting are under consideration since the release of the Export feature. I'm now working on an update to implement that as a new feature to Rath. It might be available in the online version after completed. However I need some time to rethink of details and implements about it. You can check the update in this PR (wip): #281 .

**Comment by dreamknight0** [comment]
well done~
