### ISSUE TITLE
centos server deploy rath and run it have problem

### ISSUE THREAD

**Issue by coco-boy** [Kanaries/Rath#283]
explore can not visit centos server delpoy rath, i have start it, but i can not visit, open the port, first i can visit, then it shut down,
how to deploy it in offline, without network

**Comment by ObservedObserver** [comment]
Not quite understand your questions. Can you follow a issue template so we can help you better:

## Description

Please provide a clear and concise description of the issue.

## Steps to Reproduce

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected Result

What did you expect to happen?

## Actual Result

What actually happened?

## Screenshots

If applicable, add screenshots to help explain your problem.

## Environment

- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]

## Additional Context

Add any other context about the problem here.
